import { useEffect, useState } from "react";
import { Trophy, Download, ArrowRight, Star, Share2 } from "lucide-react";

const COMP_KEY = "mentorai_completions";

function saveCompletion(goal, level, date) {
  const list = JSON.parse(localStorage.getItem(COMP_KEY) || "[]");
  if (!list.find(c => c.goal === goal)) {
    list.unshift({ goal, level, date, completedAt: Date.now() });
    localStorage.setItem(COMP_KEY, JSON.stringify(list.slice(0, 20)));
  }
}

function generateCertificate(goal, level, date) {
  const lines = [
    "╔══════════════════════════════════════════════════════╗",
    "║                                                      ║",
    "║           🎓  CERTIFICATE OF COMPLETION  🎓          ║",
    "║                                                      ║",
    "║                   MentorAI Platform                  ║",
    "║                                                      ║",
    "║  This certifies the successful completion of:        ║",
    "║                                                      ║",
    `║  Course: ${goal.padEnd(43)}║`,
    `║  Level:  ${level.padEnd(43)}║`,
    `║  Date:   ${date.padEnd(43)}║`,
    "║                                                      ║",
    "║  30-Day Learning Plan — All Days Completed ✅        ║",
    "║                                                      ║",
    "║  Skills demonstrated:                                ║",
    "║  • Consistent daily learning                         ║",
    "║  • Concept understanding                             ║",
    "║  • Hands-on practice                                 ║",
    "║  • Real-world application                            ║",
    "║                                                      ║",
    "╚══════════════════════════════════════════════════════╝",
    "",
    "Generated by MentorAI — Your Personal AI Learning Mentor",
    "mentorai.app",
  ];
  const blob = new Blob([lines.join("\n")], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `MentorAI_Certificate_${goal.replace(/\s+/g, "_")}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

// Pure CSS confetti using random divs
function Confetti() {
  const pieces = Array.from({ length: 60 }, (_, i) => ({
    id: i,
    left: `${Math.random() * 100}%`,
    delay: `${Math.random() * 3}s`,
    duration: `${2 + Math.random() * 3}s`,
    color: ["#a78bfa", "#ec4899", "#10b981", "#f59e0b", "#38bdf8", "#f87171"][Math.floor(Math.random() * 6)],
    size: `${6 + Math.random() * 8}px`,
    rotate: `${Math.random() * 360}deg`,
  }));

  return (
    <div className="confetti-container" aria-hidden="true">
      {pieces.map(p => (
        <div
          key={p.id}
          className="confetti-piece"
          style={{
            left: p.left,
            animationDelay: p.delay,
            animationDuration: p.duration,
            background: p.color,
            width: p.size,
            height: p.size,
            transform: `rotate(${p.rotate})`,
          }}
        />
      ))}
    </div>
  );
}

export default function CompletionScreen({ goal, level, onStartNext, onDismiss }) {
  const date = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
  const [shared, setShared] = useState(false);

  useEffect(() => {
    saveCompletion(goal, level, date);
  }, []);

  const shareText = `🎓 I just completed the "${goal}" 30-day learning plan on MentorAI!\n\nLevel: ${level}\nDate: ${date}\n\nLearn anything at mentorai.app`;

  const handleShare = () => {
    if (navigator.share) {
      navigator.share({ title: "Course Completed!", text: shareText });
    } else {
      navigator.clipboard.writeText(shareText);
      setShared(true);
      setTimeout(() => setShared(false), 2000);
    }
  };

  const SKILLS = [
    "Daily learning consistency",
    "Concept understanding",
    "Hands-on practice",
    "Real-world application",
    "Self-revision habits",
  ];

  return (
    <div className="completion-overlay">
      <Confetti />
      <div className="completion-card">
        <div className="completion-trophy">🏆</div>
        <div className="completion-badge">Course Completed!</div>
        <h2 className="completion-title">{goal}</h2>
        <p className="completion-subtitle">You completed all 30 days of your personalized learning plan.</p>
        <div className="completion-meta">
          <span>📊 {level}</span>
          <span>·</span>
          <span>📅 {date}</span>
          <span>·</span>
          <span>✅ 30/30 days</span>
        </div>

        {/* Skills */}
        <div className="completion-skills">
          <div className="completion-skills-title"><Star size={14} /> Skills Gained</div>
          <div className="completion-skills-list">
            {SKILLS.map((s, i) => (
              <div key={i} className="completion-skill-item">
                <span className="completion-skill-check">✓</span> {s}
              </div>
            ))}
          </div>
        </div>

        {/* Actions */}
        <div className="completion-actions">
          <button className="completion-btn primary" onClick={onStartNext}>
            <ArrowRight size={16} /> Start Next Course
          </button>
          <button className="completion-btn secondary" onClick={() => generateCertificate(goal, level, date)}>
            <Download size={16} /> Download Certificate
          </button>
          <button className="completion-btn outline" onClick={handleShare}>
            <Share2 size={16} /> {shared ? "Copied!" : "Share"}
          </button>
        </div>

        <button className="completion-dismiss" onClick={onDismiss}>
          Continue reviewing →
        </button>
      </div>
    </div>
  );
}
