// localStorage-based history and bookmarks — works offline, no auth required

const HISTORY_KEY  = "learnai_history";
const BOOKMARK_KEY = "learnai_bookmarks";
const MAX_HISTORY  = 50;

// ── History ────────────────────────────────────────────
export function saveToHistory(entry) {
  // entry: { topic, mode, level, modules, timestamp }
  const history = getHistory();
  const filtered = history.filter(h => !(h.topic === entry.topic && h.mode === entry.mode));
  const updated = [{ ...entry, timestamp: Date.now() }, ...filtered].slice(0, MAX_HISTORY);
  localStorage.setItem(HISTORY_KEY, JSON.stringify(updated));
}

export function getHistory() {
  try { return JSON.parse(localStorage.getItem(HISTORY_KEY) || "[]"); }
  catch { return []; }
}

export function deleteFromHistory(topic, mode) {
  const updated = getHistory().filter(h => !(h.topic === topic && h.mode === mode));
  localStorage.setItem(HISTORY_KEY, JSON.stringify(updated));
}

export function clearHistory() {
  localStorage.removeItem(HISTORY_KEY);
}

// ── Bookmarks ──────────────────────────────────────────
export function toggleBookmark(entry) {
  const bookmarks = getBookmarks();
  const exists = bookmarks.find(b => b.topic === entry.topic && b.mode === entry.mode);
  const updated = exists
    ? bookmarks.filter(b => !(b.topic === entry.topic && b.mode === entry.mode))
    : [{ ...entry, savedAt: Date.now() }, ...bookmarks];
  localStorage.setItem(BOOKMARK_KEY, JSON.stringify(updated));
  return !exists; // returns true if now bookmarked
}

export function getBookmarks() {
  try { return JSON.parse(localStorage.getItem(BOOKMARK_KEY) || "[]"); }
  catch { return []; }
}

export function isBookmarked(topic, mode) {
  return getBookmarks().some(b => b.topic === topic && b.mode === mode);
}

// ── Export ─────────────────────────────────────────────
export function exportAsText(topic, mode, modules) {
  const data = modules[mode] || modules.learn;
  if (!data) return;

  const lines = [
    `# ${topic} — ${mode.toUpperCase()} MODE`,
    `Generated by MentorAI | ${new Date().toLocaleDateString()}`,
    "",
  ];

  if (data.intuitive_start) lines.push("## Intuition\n" + data.intuitive_start, "");
  if (data.why_this_matters) lines.push("## Why It Matters\n" + data.why_this_matters, "");
  if (data.core_concepts?.length) {
    lines.push("## Core Concepts");
    data.core_concepts.forEach(c => {
      lines.push(`\n### ${c.name}`, c.intuitive_explanation, c.technical_explanation);
    });
    lines.push("");
  }
  if (data.subtopics?.length) {
    lines.push("## Subtopics");
    data.subtopics.forEach(s => {
      lines.push(`\n### ${s.name}`, s.deep_explanation);
      if (s.code_example) lines.push("```\n" + s.code_example + "\n```");
    });
    lines.push("");
  }
  if (data.summary) lines.push("## Summary\n" + data.summary, "");
  if (data.common_mistakes?.length) lines.push("## Common Mistakes\n" + data.common_mistakes.map(m => "- " + m).join("\n"), "");

  // Roadmap
  if (data.phases?.length) {
    lines.push("## Learning Phases");
    data.phases.forEach(p => lines.push(`\n### Phase ${p.phase}: ${p.title}`, p.description, "Topics: " + p.topics?.join(", ")));
    lines.push("");
  }

  // Interview
  if (data.questions?.length) {
    lines.push("## Interview Questions");
    data.questions.forEach((q, i) => lines.push(`\nQ${i + 1}. ${q.question}`, "Answer: " + q.answer));
    lines.push("");
  }

  const blob = new Blob([lines.join("\n")], { type: "text/plain" });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement("a");
  a.href     = url;
  a.download = `${topic.replace(/\s+/g, "_")}_${mode}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}
